# Generated by Django 4.2.11 on 2024-11-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcountdown',
            old_name='user',
            new_name='recipient',
        ),
    ]
