# Generated by Django 4.2.11 on 2024-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_gift_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcountdown',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gift_images/'),
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gift_videos/'),
        ),
    ]
