# Generated by Django 4.2.11 on 2024-11-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_giftcountdown_image_giftcountdown_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcountdown',
            name='image',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='video',
        ),
    ]
