services:
  - type: web
    name: gift-countdown-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:$PORT gift_countdown.wsgi:application --no-log-socket-errors"
    pythonVersion: 3.9
    disk:
      mountPath: /var/lib/gift_countdown
      sizeGB: 1
    envVars:
      - key: PORT
        value: "8000"