# Generated by Django 4.2.11 on 2024-11-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_giftcountdown_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='giftcountdown',
            old_name='recipient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='gift_description',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='gift_name',
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='gift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.gift'),
        ),
    ]
