# Generated by Django 4.2.11 on 2024-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gift_rename_recipient_giftcountdown_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcountdown',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='gift',
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='gift_description',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='gift_name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
