# Generated by Django 4.2.11 on 2024-11-04 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_giftcountdown_gift_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gift', 'verbose_name_plural': 'Gifts'},
        ),
        migrations.AlterModelOptions(
            name='giftcountdown',
            options={'ordering': ['countdown_date'], 'verbose_name': 'Gift Countdown', 'verbose_name_plural': 'Gift Countdowns'},
        ),
        migrations.AddField(
            model_name='gift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this gift was created', null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this gift is active and can be used in new countdowns'),
        ),
        migrations.AddField(
            model_name='gift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this gift was last updated'),
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this countdown was created', null=True),
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this countdown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_countdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='gift',
            field=models.ForeignKey(help_text='The gift being counted down to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countdowns', to='main.gift'),
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='When the recipient opened the gift', null=True),
        ),
        migrations.AddField(
            model_name='giftcountdown',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Open'), ('opened', 'Opened'), ('expired', 'Expired')], default='pending', help_text='Current status of the countdown', max_length=20),
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(help_text='Detailed description of the gift'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(help_text='Name of the gift', max_length=255),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='countdown_date',
            field=models.DateTimeField(help_text='When the gift will be revealed'),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='gift_description',
            field=models.TextField(help_text='Description of the gift (copied from Gift for data preservation)', null=True),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='gift_name',
            field=models.CharField(help_text='Name of the gift (copied from Gift for data preservation)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='recipient',
            field=models.ForeignKey(help_text='User who will receive the gift', on_delete=django.db.models.deletion.CASCADE, related_name='gift_countdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='giftcountdown',
            index=models.Index(fields=['countdown_date'], name='main_giftco_countdo_35b926_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcountdown',
            index=models.Index(fields=['status'], name='main_giftco_status_3e2a1c_idx'),
        ),
    ]
