# Generated by Django 4.2.11 on 2024-11-04 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_gift_options_alter_giftcountdown_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={},
        ),
        migrations.AlterModelOptions(
            name='giftcountdown',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='giftcountdown',
            name='main_giftco_countdo_35b926_idx',
        ),
        migrations.RemoveIndex(
            model_name='giftcountdown',
            name='main_giftco_status_3e2a1c_idx',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='opened_at',
        ),
        migrations.RemoveField(
            model_name='giftcountdown',
            name='status',
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='countdown_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='gift_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='gift_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
