# Generated by Django 4.2.11 on 2024-11-04 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_gift_options_alter_giftcountdown_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'permissions': [('can_view_gift', 'Can view gift details')]},
        ),
        migrations.AddField(
            model_name='gift',
            name='countdown_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
