# Generated by Django 4.2.11 on 2024-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_gift_options_gift_countdown_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='giftcountdown',
            name='countdown_date',
            field=models.DateTimeField(null=True),
        ),
    ]
